---
- name: Initialize OS setting for Windows Servers
  hosts: windows_servers

  tasks:
    - name: git_test script
      script: windows_Script/git_sample_Code.ps1

#    # Install a Windows feature and reboot if necessary
#    - name: Install IIS Web-Server
#      ansible.windows.win_feature:
#        name: Web-Server
#      register: iis_install

#    - name: Reboot when Web-Server feature requires it
#      ansible.windows.win_reboot:
#      when: iis_install.reboot_required

      # 強制で再起動してしまうため、コメントアウト
#    - name: Reboot
#      win_reboot:
#        post_reboot_delay: 3600
